from __future__ import annotations

from backend.config.thresholds import MIN_CANDIDATE_SCORE, PREVIEW_TOP_K

RANKING_STAGE_WEIGHTS = {
    "hook_quality": 0.25,
    "narrative": 0.20,
    "context": 0.15,
    "density": 0.15,
    "retention": 0.15,
    "novelty": 0.10,
}

CONFIDENCE_HIGH = 0.85
CONFIDENCE_MODERATE = 0.60
CONFIDENCE_LOW = 0.40
CONFIDENCE_ELIMINATE = 0.0

MIN_DURATION_SECONDS = 15
MAX_DURATION_SECONDS = 90
MAX_GAP_SECONDS = 30
MIN_RAW_SCORE = 0.15

TIE_BREAKING_ORDER = [
    "confidence",
    "hook_quality",
    "duration",
    "position",
]

SEMANTIC_SIMILARITY_THRESHOLD = 0.75
NOVELTY_HOOK_THRESHOLD = 2.0
NOVELTY_BODY_THRESHOLD = 5.0

NARRATIVE_PENALTY_THRESHOLD = 0.3
NARRATIVE_PENALTY_FACTOR = 0.7

CONTEXT_PENALTY_THRESHOLD = 0.3
CONTEXT_PENALTY_FACTOR = 0.8

HOOK_IDEAL_MIN = 3
HOOK_IDEAL_MAX = 7
HOOK_ACCEPTABLE_MIN = 2
HOOK_ACCEPTABLE_MAX = 10

DENSITY_IDEAL_MIN = 2.5
DENSITY_IDEAL_MAX = 3.5
DENSITY_ACCEPTABLE_MIN = 1.5
DENSITY_ACCEPTABLE_MAX = 4.5

RETENTION_IDEAL_MIN = 30
RETENTION_IDEAL_MAX = 60
RETENTION_ACCEPTABLE_MIN = 20
RETENTION_ACCEPTABLE_MAX = 75

PRUNING_MAX_HOOKS = 15
PRUNING_MAX_BODIES = 40
PRUNING_MAX_ENDINGS = 10
PRUNING_MIN_SEGMENT_SCORE = 0.2

GLOBAL_OPTIMIZATION_LAMBDA_QUALITY = 0.7
GLOBAL_OPTIMIZATION_LAMBDA_DIVERSITY = 0.3
GLOBAL_OPTIMIZATION_TOP_K = PREVIEW_TOP_K

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_FALLBACK = "tfidf"

FINAL_RANKING_RAW_SCORE_BOOST = 0.3
FINAL_RANKING_STAGE_WEIGHT = 0.7
